export const translations: { [key: number]: { [key: string]: string } } = {
  // English (lid: 1)
  1: {
    tab_news: "Article News",
    tab_ai_news: "AI Briefs",
    tab_hourly_top: "Top",
    tab_radio: "Radio",
    title_news: "Article News",
    title_ai_news: "AI Briefs",
    title_hourly_top: "Top",
    title_radio: "Radio",
    btn_refresh: "Refresh",
    btn_contact: "Contact Us",
    btn_report: "Report a Problem",
    report_title: "Report a Problem",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "Cancel",
    btn_submit: "Save",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "Failed : load headlines.\nTap : retry or refresh.",
    no_news: "No results found.",
    no_briefs: "No results found.",
    no_briefs_sub: "No updates published yet.",
    conn_error: "No Internet Connection.\nPlease check your connection and try again.",
    change_filter: "No %s news found yet. Try loading more headlines.",
    contact_title: "Support",
    contact_email: "Email Support",
    contact_phone: "Phone Support",
    contact_hours: "24/7"
  },
  // Gujarati (lid: 3)
  3: {
    tab_news: "સમાચાર",
    tab_ai_news: "એઆઈ બ્રીફ",
    tab_hourly_top: "ટોપ હેડલાઇન્સ",
    tab_radio: "લાઇવ રેડિયો",
    title_news: "સમાચાર",
    title_ai_news: "એઆઈ બ્રીફ",
    title_hourly_top: "ટોપ હેડલાઇન્સ",
    title_radio: "લાઇવ રેડિયો",
    btn_refresh: "રિફ્રેશ",
    btn_contact: "સંપર્ક કરો",
    btn_report: "સમસ્યાની જાણ કરો",
    report_title: "સમસ્યાની જાણ કરો",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "રદ કરો",
    btn_submit: "સાચવો",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "હેડલાઇન્સ લોડ કરવામાં નિષ્ફળ.\nફરીથી પ્રયાસ કરવા અથવા રિફ્રેશ કરવા માટે ટેપ કરો.",
    no_news: "કોઈ પરિણામ મળ્યું નથી.",
    no_briefs: "કોઈ પરિણામ મળ્યું નથી.",
    no_briefs_sub: "No updates published yet.",
    conn_error: "કોઈ ઇન્ટરનેટ કનેક્શન નથી.\nકૃપા કરીને તમારું કનેક્શન તપાસો અને ફરીથી પ્રયાસ કરો.",
    change_filter: "હજી સુધી કોઈ %s સમાચાર મળ્યા નથી. વધુ સમાચાર લોડ કરો.",
    contact_title: "સહાય",
    contact_email: "ઈમેલ સપોર્ટ",
    contact_phone: "ફોન સપોર્ટ",
    contact_hours: "24/7"
  },
  // Hindi (lid: 4)
  4: {
    tab_news: "समाचार",
    tab_ai_news: "एआई ब्रीफ",
    tab_hourly_top: "टॉप सुर्खियां",
    tab_radio: "लाइव रेडियो",
    title_news: "समाचार",
    title_ai_news: "एआई ब्रीफ",
    title_hourly_top: "टॉप सुर्खियां",
    title_radio: "लाइव रेडियो",
    btn_refresh: "रिफ्रेश",
    btn_contact: "संपर्क करें",
    btn_report: "समस्या की रिपोर्ट करें",
    report_title: "समस्या की रिपोर्ट करें",
    report_prompt: "रिपोर्ट करने का कारण चुनें:",
    reason_spam: "स्पैम / गलत जानकारी",
    reason_broken: "टूटा हुआ लिंक",
    reason_inappropriate: "अनुचित सामग्री",
    reason_copyright: "कॉपीराइट मुद्दा",
    btn_cancel: "रद्द करें",
    btn_submit: "सहेजें",
    report_success: "रिपोर्ट सबमिट की गई!",
    report_fail: "रिपोर्ट विफल रही।",
    news_source: "स्रोत",
    end_of_list: "आप सूची के अंत तक पहुँच चुके हैं।",
    failed_load: "सुर्खियां लोड करने में विफल।\nपुन: प्रयास करने या ताज़ा करने के लिए टैप करें।",
    no_news: "कोई परिणाम नहीं मिला।",
    no_briefs: "कोई परिणाम नहीं मिला।",
    no_briefs_sub: "No updates published yet.",
    conn_error: "कोई इंटरनेट कनेक्शन नहीं।\nकृपया अपना कनेक्शन जांचें और पुन: प्रयास करें।",
    change_filter: "%s समाचार अभी नहीं मिला। और सुर्खियां लोड करें।",
    contact_title: "सहायता",
    contact_email: "ईमेल सहायता",
    contact_phone: "फोन सहायता",
    contact_hours: "24/7"
  },
  // Kannada (lid: 5)
  5: {
    tab_news: "ಸುದ್ದಿಗಳು",
    tab_ai_news: "ಐಎ ಸಾರಾಂಶ",
    tab_hourly_top: "ಟಾಪ್ ಹೆಡ್‌ಲೈನ್ಸ್",
    tab_radio: "ಲೈವ್ ರೇಡಿಯೋ",
    title_news: "ಸುದ್ದಿಗಳು",
    title_ai_news: "ಐಎ ಸಾರಾಂಶ",
    title_hourly_top: "ಟಾಪ್ ಹೆಡ್‌ಲೈನ್ಸ್",
    title_radio: "ಲೈವ್ ರೇಡಿಯೋ",
    btn_refresh: "ರಿಫ್ರೆಶ್ ಮಾಡಿ",
    btn_contact: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
    btn_report: "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    report_title: "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "ರದ್ದುಗೊಳಿಸಿ",
    btn_submit: "ಉಳಿಸಿ",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "ಮುಖ್ಯಾಂಶಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ.\nಮತ್ತೆ ಪ್ರಯತ್ನಿಸಲು ಅಥವಾ ರಿಫ್ರೆಶ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ.",
    no_news: "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    no_briefs: "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    no_briefs_sub: "No updates published yet.",
    conn_error: "ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ.\nದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    change_filter: "ಇನ್ನೂ ಯಾವುದೇ %s ಸುದ್ದಿ ಕಂಡುಬಂದಿಲ್ಲ. ಇನ್ನಷ್ಟು ಲೋಡ್ ಮಾಡಿ.",
    contact_title: "ಬೆಂಬಲ",
    contact_email: "ಇಮೇಲ್ ಬೆಂಬಲ",
    contact_phone: "ಫೋನ್ ಬೆಂಬಲ",
    contact_hours: "24/7"
  },
  // Malayalam (lid: 6)
  6: {
    tab_news: "വാർത്തകൾ",
    tab_ai_news: "എഐ ചുരുക്കം",
    tab_hourly_top: "പ്രധാന വാർത്തകൾ",
    tab_radio: "ലൈവ് റേഡിയോ",
    title_news: "വാർത്തകൾ",
    title_ai_news: "എഐ ചുരുക്കം",
    title_hourly_top: "പ്രധാന വാർത്തകൾ",
    title_radio: "ലൈവ് റേഡിയോ",
    btn_refresh: "റിഫ്രഷ് ചെയ്യുക",
    btn_contact: "ഞങ്ങളെ ബന്ധപ്പെടുക",
    btn_report: "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
    report_title: "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "റദ്ദാക്കുക",
    btn_submit: "സേവ് ചെയ്യുക",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "വാർത്തകൾ ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു.\nവീണ്ടും ശ്രമിക്കാൻ ടാപ്പ് ചെയ്യുക.",
    no_news: "ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല.",
    no_briefs: "ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല.",
    no_briefs_sub: "No updates published yet.",
    conn_error: "ഇന്റർനെറ്റ് കണക്ഷൻ ഇല്ല.\nദയവായി നിങ്ങളുടെ കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.",
    change_filter: "ഇതുവരെ %s വാർത്തകളൊന്നും കണ്ടെത്തിയില്ല. കൂടുതൽ ലോഡ് ചെയ്യുക.",
    contact_title: "പിന്തുണ",
    contact_email: "ഇമെയിൽ പിന്തുണ",
    contact_phone: "ഫോൺ പിന്തുണ",
    contact_hours: "24/7"
  },
  // Marathi (lid: 7)
  7: {
    tab_news: "बातम्या",
    tab_ai_news: "एआय ब्रीफ",
    tab_hourly_top: "टॉप हेडलाईन्स",
    tab_radio: "लाईव्ह रेडिओ",
    title_news: "बातम्या",
    title_ai_news: "एआय ब्रीफ",
    title_hourly_top: "टॉप हेडलाईन्स",
    title_radio: "लाईव्ह रेडिओ",
    btn_refresh: "रिफ्रेश",
    btn_contact: "आमच्याशी संपर्क साधा",
    btn_report: "समस्या नोंदवा",
    report_title: "समस्या नोंदवा",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "रद्द करा",
    btn_submit: "जतन करा",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "हेडलाईन्स लोड करण्यात अपयशी.\nपुन्हा प्रयत्न करण्यासाठी किंवा रिफ्रेश करण्यासाठी टॅप करा.",
    no_news: "कोणतेही निकाल आढळले नाहीत.",
    no_briefs: "कोणतेही निकाल आढळले नाहीत.",
    no_briefs_sub: "No updates published yet.",
    conn_error: "इंटरनेट कनेक्शन नाही.\nकृपया तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.",
    change_filter: "%s बातम्या आढळल्या नाहीत. अधिक बातम्या लोड करा.",
    contact_title: "मदत",
    contact_email: "ईमेल सपोर्ट",
    contact_phone: "फोन सपोर्ट",
    contact_hours: "24/7"
  },
  // punjabiText (lid: 9)
  9: {
    tab_news: "ਸਮਾਚਾਰ",
    tab_ai_news: "ਏਆਈ ਬ੍ਰੀਫ",
    tab_hourly_top: "ਟੌਪ ਹੈੱਡਲਾਈਨਜ਼",
    tab_radio: "ਲਾਈਵ ਰੇਡੀਓ",
    title_news: "ਸਮਾਚਾਰ",
    title_ai_news: "ਏਆਈ ਬ੍ਰੀਫ",
    title_hourly_top: "ਟੌਪ ਹੈੱਡਲਾਈਨਜ਼",
    title_radio: "ਲਾਈਵ ਰੇਡੀਓ",
    btn_refresh: "ਰਿਫ੍ਰੈਸ਼",
    btn_contact: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    btn_report: "ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ",
    report_title: "ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "ਰੱਦ ਕਰੋ",
    btn_submit: "ਸੇਵ ਕਰੋ",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "ਸੁਰਖੀਆਂ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।\nਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰਨ ਜਾਂ ਰਿਫ੍ਰੈਸ਼ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ।",
    no_news: "ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ।",
    no_briefs: "ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ।",
    no_briefs_sub: "No updates published yet.",
    conn_error: "ਕੋਈ ਇੰਟਰਨੈਟ ਕਨੈਕਸ਼ਨ ਨਹੀਂ।\nਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਕਨੈਕਸ਼ਨ ਚੈੱਕ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    change_filter: "ਅਜੇ ਕੋਈ %s ਖ਼ਬਰਾਂ ਨਹੀਂ ਮਿਲੀਆਂ। ਹੋਰ ਖ਼ਬਰਾਂ ਲੋਡ ਕਰੋ।",
    contact_title: "ਸਹਾਇਤਾ",
    contact_email: "ਈਮੇਲ ਸਹਾਇਤਾ",
    contact_phone: "ਫੋਨ ਸਹਾਇਤਾ",
    contact_hours: "24/7"
  },
  // Tamil (lid: 10)
  10: {
    tab_news: "செய்திகள்",
    tab_ai_news: "ஏஐ சுருக்கம்",
    tab_hourly_top: "தலைப்புச் செய்திகள்",
    tab_radio: "நேரலை வானொலி",
    title_news: "செய்திகள்",
    title_ai_news: "ஏஐ சுருக்கம்",
    title_hourly_top: "தலைப்புச் செய்திகள்",
    title_radio: "நேரலை வானொலி",
    btn_refresh: "புதுப்பி",
    btn_contact: "எங்களை தொடர்பு கொள்ள",
    btn_report: "சிக்கலைப் புகாரளி",
    report_title: "சிக்கலைப் புகாரளி",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "ரத்து செய்",
    btn_submit: "சேமி",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "தலைப்புச் செய்திகளை ஏற்ற முடியவில்லை.\nமீண்டும் முயற்சிக்க அல்லது புதுப்பிக்க தட்டவும்.",
    no_news: "முடிவுகள் எதுவும் காணப்படவில்லை.",
    no_briefs: "முடிவுகள் எதுவும் காணப்படவில்லை.",
    no_briefs_sub: "No updates published yet.",
    conn_error: "இணைய இணைப்பு இல்லை.\nஉங்கள் இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
    change_filter: "%s செய்திகள் எதுவும் கிடைக்கவில்லை. மேலும் ஏற்றவும்.",
    contact_title: "ஆதரவு",
    contact_email: "மின்னஞ்சல் ஆதரவு",
    contact_phone: "தொலைபேசி ஆதரவு",
    contact_hours: "24/7"
  },
  // Telugu (lid: 11)
  11: {
    tab_news: "వార్తలు",
    tab_ai_news: "ఏఐ బ్రీఫ్స్",
    tab_hourly_top: "టాప్ హెడ్‌లైన్స్",
    tab_radio: "లైవ్ రేడియో",
    title_news: "వార్తలు",
    title_ai_news: "ఏఐ బ్రీఫ్స్",
    title_hourly_top: "టాప్ హెడ్‌లైన్స్",
    title_radio: "లైవ్ రేడియో",
    btn_refresh: "రిఫ్రెష్ చేయండి",
    btn_contact: "మమ్మల్ని సంప్రదించండి",
    btn_report: "సమస్యను నివేదించండి",
    report_title: "సమస్యను నివేదించండి",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "రద్దు చేయి",
    btn_submit: "సేవ్ చేయి",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "ముఖ్యాంశాలను లోడ్ చేయడంలో విఫలమైంది.\nమళ్లీ ప్రయత్నించడానికి లేదా రిఫ్రెష్ చేయడానికి నొక్కండి.",
    no_news: "ఫలితాలు కనుగొనబడలేదు.",
    no_briefs: "ఫలితాలు కనుగొనబడలేదు.",
    no_briefs_sub: "No updates published yet.",
    conn_error: "ఇంటర్నెట్ కనెక్షన్ లేదు.\nదయచేసి మీ కనెక్షన్‌ని తనిఖీ చేసి, మళ్లీ ప్రయత్నించండి.",
    change_filter: "ఇంకా %s వార్తలు కనుగొనబడలేదు. మరిన్ని వార్తలను లోడ్ చేయండి.",
    contact_title: "మద్దతు",
    contact_email: "ఈమెయిల్ మద్దతు",
    contact_phone: "ఫోన్ మద్దతు",
    contact_hours: "24/7"
  },
  // Urdu (lid: 12)
  12: {
    tab_news: "خبریں",
    tab_ai_news: "اے آئی خلاصہ",
    tab_hourly_top: "اہم خبریں",
    tab_radio: "لائیو ریڈیو",
    title_news: "خبریں",
    title_ai_news: "اے آئی خلاصہ",
    title_hourly_top: "اہم خبریں",
    title_radio: "لائیو ریڈیو",
    btn_refresh: "ریفریش",
    btn_contact: "ہم سے رابطہ کریں",
    btn_report: "مسئلہ رپورٹ کریں",
    report_title: "مسئلہ رپورٹ کریں",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "منسوخ کریں",
    btn_submit: "محفوظ کریں",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "سرخیاں لوڈ کرنے میں ناکام۔\nدوبارہ کوشش کرنے یا ریفریش کرنے کے لیے ٹیپ کریں۔",
    no_news: "کوئی نتیجہ نہیں ملا。",
    no_briefs: "کوئی نتیجہ نہیں ملا。",
    no_briefs_sub: "No updates published yet.",
    conn_error: "انٹرنیٹ کنکشن نہیں ہے۔\nبراہ کرم اپنا کنکشن چیک کریں اور دوبارہ کوشش کریں۔",
    change_filter: "ابھی تک %s کی کوئی خبر نہیں ملی۔ مزید خبریں لوڈ کریں۔",
    contact_title: "مدد",
    contact_email: "ای میل سپورٹ",
    contact_phone: "فون سپورٹ",
    contact_hours: "24/7"
  },
  // Bengali (lid: 14)
  14: {
    tab_news: "সংবাদ",
    tab_ai_news: "এআই ব্রিফ",
    tab_hourly_top: "টপ হেডলাইন",
    tab_radio: "লাইভ রেডিও",
    title_news: "সংবাদ",
    title_ai_news: "এআই ব্রিফ",
    title_hourly_top: "টপ হেডলাইন",
    title_radio: "লাইভ রেডিও",
    btn_refresh: "রিফ্রেশ",
    btn_contact: "যোগাযোগ করুন",
    btn_report: "সমস্যার রিপোর্ট করুন",
    report_title: "সমস্যার রিপোর্ট করুন",
    report_prompt: "Choose a reason to report this link:",
    reason_spam: "Spam / False Information",
    reason_broken: "Broken Link / Not Loading",
    reason_inappropriate: "Inappropriate Content",
    reason_copyright: "Copyright / IP Issue",
    btn_cancel: "বাতিল করুন",
    btn_submit: "সংরক্ষণ করুন",
    report_success: "Report submitted successfully!",
    report_fail: "Failed to submit report. Please try again.",
    news_source: "Source",
    end_of_list: "You have reached the end of the list.",
    failed_load: "শিরোনাম লোড করতে ব্যর্থ।\nআবার চেষ্টা করতে বা রিফ্রেশ করতে ট্যাপ করুন।",
    no_news: "কোনো ফলাফল পাওয়া যায়নি।",
    no_briefs: "কোনো ফলাফল পাওয়া যায়নি।",
    no_briefs_sub: "No updates published yet.",
    conn_error: "কোনো ইন্টারনেট সংযোগ নেই।\nঅনুগ্রহ করে আপনার সংযোগ পরীক্ষা করুন এবং আবার চেষ্টা করুন।",
    change_filter: "%s খবর পাওয়া যায়নি। আরো খবর লোড করুন।",
    contact_title: "সহায়তা",
    contact_email: "ইমেল সহায়তা",
    contact_phone: "ফোন সহায়তা",
    contact_hours: "24/7"
  },
};

export const categoryTranslations: { [key: number]: { [key: string]: string } } = {
  // English
  1: {
    "all": "All",
    "india": "India",
    "world": "World",
    "business": "Business",
    "sports": "Sports",
    "entertainment": "Entertainment",
  },
  // Gujarati
  3: {
    "all": "બધા",
    "india": "ભારત",
    "world": "વિશ્વ",
    "business": "બિઝનેસ",
    "sports": "રમતગમત",
    "entertainment": "મનોરંજન",
    "technology": "ટેકનોલોજી",
    "health": "આરોગ્ય",
    "science": "વિજ્ઞાન",
    "politics": "રાજકારણ",
    "education": "શિક્ષણ",
    "auto": "ઓટો",
    "travel": "પ્રવાસ",
    "lifestyle": "જીવનશૈલી",
  },
  // Hindi
  4: {
    "all": "सभी",
    "india": "भारत",
    "world": "विश्व",
    "business": "व्यापार",
    "sports": "खेल",
    "entertainment": "मनोरंजन",
  },
  // Kannada
  5: {
    "all": "ಎಲ್ಲಾ",
    "india": "ಭಾರತ",
    "world": "ವಿಶ್ವ",
    "business": "ವ್ಯಾಪಾರ",
    "sports": "ಕ್ರೀಡೆ",
    "entertainment": "ಮನರಂಜನೆ",
    "technology": "ತಂತ್ರಜ್ಞಾನ",
    "health": "ಆರೋಗ್ಯ",
    "science": "ವಿಜ್ಞಾನ",
    "politics": "ರಾಜಕೀಯ",
    "education": "ಶಿಕ್ಷಣ",
    "auto": "ಆಟೋ",
    "travel": "ಪ್ರಯಾಣ",
    "lifestyle": "ಜೀವನಶೈಲಿ",
  },
  // Malayalam
  6: {
    "all": "എല്ലാം",
    "india": "ഇന്ത്യ",
    "world": "ലോകം",
    "business": "ബിസിനസ്",
    "sports": "കായികം",
    "entertainment": "വിനോദം",
    "technology": "സാങ്കേതികം",
    "health": "ആരോഗ്യം",
    "science": "ശാസ്ത്രം",
    "politics": "രാഷ്ട്രീയം",
    "education": "വിദ്യാഭ്യാസം",
    "auto": "ഓട്ടോ",
    "travel": "യാത്ര",
    "lifestyle": "ജീവിതശൈലി",
  },
  // Marathi
  7: {
    "all": "सर्व",
    "india": "भारत",
    "world": "विश्व",
    "business": "व्यवसाय",
    "sports": "क्रीडा",
    "entertainment": "मनोरंजन",
    "technology": "तंत्रज्ञान",
    "health": "आरोग्य",
    "science": "विज्ञान",
    "politics": "राजकारण",
    "education": "शिक्षण",
    "auto": "ऑटो",
    "travel": "प्रवास",
    "lifestyle": "जीवनशैली",
  },
  // punjabiText
  9: {
    "all": "ਸਭ",
    "india": "ਭਾਰਤ",
    "world": "ਦੁਨੀਆ",
    "business": "ਕਾਰੋਬਾਰ",
    "sports": "ਖੇਡਾਂ",
    "entertainment": "ਮਨੋਰੰਜਨ",
    "technology": "ਤਕਨਾਲੋਜੀ",
    "health": "ਸਿਹਤ",
    "science": "ਵਿਗਿਆਨ",
    "politics": "ਰਾਜਨੀਤੀ",
    "education": "ਸਿੱਖਿਆ",
    "auto": "ਆਟੋ",
    "travel": "ਯਾਤਰਾ",
    "lifestyle": "ਜੀਵਨ ਸ਼ੈਲੀ",
  },
  // Tamil
  10: {
    "all": "அனைத்தும்",
    "india": "இந்தியா",
    "world": "உலகம்",
    "business": "வணிகம்",
    "sports": "விளையாட்டு",
    "entertainment": "பொழுதுபோக்கு",
    "technology": "தொழில்நுட்பம்",
    "health": "ஆரோக்கியம்",
    "science": "அறிவியல்",
    "politics": "அரசியல்",
    "education": "கல்வி",
    "auto": "ஆட்டோ",
    "travel": "பயணம்",
    "lifestyle": "வாழ்க்கை முறை",
  },
  // Telugu
  11: {
    "all": "అన్నీ",
    "india": "భారత్",
    "world": "ప్రపంచం",
    "business": "వ్యాపారం",
    "sports": "క్రీడలు",
    "entertainment": "వినోదం",
    "technology": "టెక్నాలజీ",
    "health": "ఆరోగ్యం",
    "science": "విజ్ఞానం",
    "politics": "రాజకీయాలు",
    "education": "విద్య",
    "auto": "ఆటో",
    "travel": "ప్రయాణం",
    "lifestyle": "జీవనశైలి",
  },
  // Urdu
  12: {
    "all": "سب",
    "india": "بھارت",
    "world": "دنیا",
    "business": "کاروبار",
    "sports": "کھیل",
    "entertainment": "تفریح",
    "technology": "ٹیکنالوجی",
    "health": "صحت",
    "science": "سائنس",
    "politics": "سیاست",
    "education": "تعلیم",
    "auto": "آٹو",
    "travel": "سفر",
    "lifestyle": "طرز زندگی",
  },
  // Bengali
  14: {
    "all": "সব",
    "india": "ভারত",
    "world": "বিশ্ব",
    "business": "ব্যবসা",
    "sports": "খেলাধুলা",
    "entertainment": "বিনোদন",
    "technology": "প্রযুক্তি",
    "health": "স্বাস্থ্য",
    "science": "বিজ্ঞান",
    "politics": "রাজনীতি",
    "education": "শিক্ষা",
    "auto": "অটো",
    "travel": "ভ্রমণ",
    "lifestyle": "জীবনধারা",
  },
};

export function t(languageId: number, key: string): string {
  const lang = translations[languageId] || translations[1];
  return lang[key] || translations[1][key] || key;
}

export function tCategory(languageId: number, categoryId: string): string {
  const lang = categoryTranslations[languageId] || categoryTranslations[1];
  return lang[categoryId] || categoryTranslations[1][categoryId] || categoryId;
}
